type Mistake @table(key: ["userId", "questionId"]) {
  userId: String! @col(name: "user_id")
  questionId: String! @col(name: "question_id")
  category: String!
  topic: String!
  type: String!
  mistakeType: String!
  userOverrideType: String
  firstIncorrectAt: Timestamp!
  lastIncorrectAt: Timestamp!
  timesIncorrect: Int!
  isResolved: Boolean!
  resolvedAt: Timestamp
  userNote: String
}
